apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        dapr.io/app-id: notification-service
        dapr.io/app-port: '4002'
        dapr.io/app-protocol: http
        dapr.io/enabled: 'true'
        dapr.io/config: "./config.yaml"        
        #dapr.io/dapr-http-port: '3502' # Set the Dapr sidecar port
        
    spec:
      containers:
        - name: notification-service
          image: priyeshnayak/dapr_test_app-notification-service:latest
          ports:
            - containerPort: 4002
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - name: app-port
      protocol: TCP
      port: 80 # You can use the port you prefer
      targetPort: 4002 # The port your application is listening on in the pod              
    - name: dapr-port
      protocol: TCP
      port: 3502 # You can use the port you prefer
      targetPort: 3502       